#!/usr/bin/bash
RED='\033[0;31m'
GREEN='\033[0;32m'

help() {
	echo "Syntax: rn [file_name] [testcase_postition]"
}

if [ "$1" == "-h" ] ; then
	help
    exit 0
fi

set -e
build $1
v=$(<num.txt)
fl=1

result=()
run_test () {
    start_time=$(date +%s.%3N)
    ./$2 < in$1.txt > ans$1.txt
    end_time=$(date +%s.%3N)
    elapsed=$(echo "($end_time - $start_time) * 1000" | bc)
    result+=($elapsed)

	echo $(cat out$1.txt | trim) > output
	echo $(cat ans$1.txt | trim) > answer
	if !(cmp -s output answer)
    then
        fl=0
        echo -e $"\e[1mInput:\e[0m"
        cat in$1.txt
        echo -e $"\e[1mExpected:\e[0m"
        cat out$1.txt 
        echo -e $"\e[1mOutput:\e[0m"
        cat ans$1.txt
        echo $""
        echo $""
    fi
    # printf "elapsed: %.3f ms\n" $elapsed
}


if [ "$2" ]
then
	v=1
	run_test $2 $1
else
for ((i=1;i<=v;i++))
do
	run_test $i $1
done
fi



if [ $fl -eq 1 ]
then
    if [ $v -eq 1 ]; then echo -e "Passed 1 test"; else echo -e "Passed $v tests"; fi
# else
#     echo -e "Wrong answer!"
fi

echo ""
index=1
for value in "${result[@]}"
do
    printf "elapsed %d: %.0f ms\n" $index $value 
    ((index++))
done
